variables:
    # Use a shallow clone depth to speed up the CI build.
    # See: https://docs.gitlab.com/ee/ci/large_repositories/
    BUILD_NAME: Traffic3D
    GIT_DEPTH: 10
    DOCKER_IMAGE_NAME: "$CI_REGISTRY_IMAGE"
    DOCKER_BUILD_ARGS: BUILDKIT_INLINE_CACHE=1
    FEATURE_BRANCH_TAG: $CI_COMMIT_REF_SLUG


cache:
    key: "$CI_PROJECT_NAMESPACE-$CI_PROJECT_NAME-$CI_COMMIT_REF_SLUG-$BUILD_TARGET"
    paths:
        - .apt/
        - $BUILD_NAME/Library/

stages:
    - lint
    - test
    - build
    - prepare-benchmark
    - benchmark

workflow:
    rules:
        - if: $CI_MERGE_REQUEST_ID
          when: never
        - if: $CI_COMMIT_TAG
          when: always
        - when: always

lint:mdl:
    stage: lint
    image: ruby:2.7
    before_script:
        - gem install mdl
    script:
        - git ls-files -z '*.md' | xargs -0 mdl --style .mdl.rb
    rules:
        - when: always
    tags:
        - shared

lint:metalint:
    stage: lint
    script:
        - chmod +x ci/metalint.sh
        - ./ci/metalint.sh
    rules:
        - when: always
    tags:
        - shared

.test: &test
    image: gableroux/unity3d:2018.3.11f1
    stage: test
    before_script:
        # Configure apt cache.
        - export APT_DIR=.apt
        - export APT_STATE_LISTS=$APT_DIR/lists
        - export APT_CACHE_ARCHIVES=$APT_DIR/archives
        - mkdir -p $APT_CACHE_ARCHIVES/partial
        # Update apt-get lists and install new packages.
        - apt-get update -yqq
        - apt-get install --no-install-recommends -y  -o dir::cache::archives="$APT_CACHE_ARCHIVES" libsaxonb-java
        # Prepare CI for test jobs.
        - &unity-before-script chmod +x ./ci/before_script.sh && ./ci/before_script.sh
        - chmod +x ./ci/test.sh && ./ci/test.sh
    script:
        - test -f $CI_PROJECT_DIR/$TEST_PLATFORM-results.xml
        - saxonb-xslt -s $CI_PROJECT_DIR/$TEST_PLATFORM-results.xml -xsl $CI_PROJECT_DIR/ci/nunit-transforms/nunit3-junit.xslt >$CI_PROJECT_DIR/$TEST_PLATFORM-junit-results.xml
        - test -f $CI_PROJECT_DIR/$TEST_PLATFORM-junit-results.xml
    artifacts:
        when: always
        reports:
            junit: $CI_PROJECT_DIR/$TEST_PLATFORM-junit-results.xml
        expire_in: 2 weeks
    # No rules means on_success is applied on all branches by default.
    tags:
        - shared

test-playmode:
    <<: *test
    variables:
        TEST_PLATFORM: playmode

test-editmode:
    <<: *test
    variables:
        TEST_PLATFORM: editmode


.build: &build
    image: gableroux/unity3d:2018.3.11f1
    stage: build
    before_script:
        - *unity-before-script
    script:
        - chmod +x ./ci/build.sh && ./ci/build.sh
    parallel:
        matrix:
            - BUILD_TARGET:
                  - StandaloneLinux64
                  - StandaloneOSX
                  - StandaloneWindows64
    tags:
        - shared

build:feature-branch:
    <<: *build
    artifacts:
        paths:
            - ./$BUILD_NAME/Builds/
        expire_in: 1 week
    rules:
        - if: $CI_COMMIT_TAG
          when: never
        - if: '$CI_COMMIT_BRANCH == "master"'
          when: never
        - when: on_success

build:master:
    <<: *build
    artifacts:
        paths:
            - ./$BUILD_NAME/Builds/
        expire_in: never
    rules:
        - if: '$CI_COMMIT_BRANCH == "master"'
          when: on_success
        - when: never

prepare-benchmark:
    stage: prepare-benchmark
    image: docker:stable
    variables:
        DOCKER_TLS_CERTDIR: ""
    services:
        - docker:dind
    script:
        - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
        - cd .meta
        # Note that, unlike $BUILD_NAME, $PROJECT_NAME is lowercase, and so
        # won't cause Docker to error with:
        #     invalid reference format: repository name must be lowercase
        - docker build -t $DOCKER_IMAGE_NAME:$FEATURE_BRANCH_TAG --build-arg $DOCKER_BUILD_ARGS .
        - docker push $DOCKER_IMAGE_NAME:$FEATURE_BRANCH_TAG
    rules:
        - when: manual
          allow_failure: true
    tags:
        - shared

benchmark:
    stage: benchmark
    image: $DOCKER_IMAGE_NAME:$FEATURE_BRANCH_TAG
    needs: [prepare-benchmark]
    before_script:
        - *unity-before-script
    script:
        - chmod +x ./ci/benchmark.sh && ./ci/benchmark.sh
    rules:
        - when: manual
          allow_failure: true
    tags:
        - shared
