public enum SensorType
{
    FRONT_COLLISION_SENSOR,
    SURFACE_SENSOR,
    DEADLOCK_SENSOR,
    MERGE_SENSOR,
    CORNER_SPEED_SENSOR,
    STOP_LINE_SENSOR,
    STOP_NODE_SENSOR,
    SPEED_LIMIT_SENSOR,
    TRAFFIC_LIGHT_SENSOR
}
